### ISSUE TITLE
Dijkstra not working with Unreachable nodes

### ISSUE THREAD

**Issue by pedronaresi** [brianstorti/ruby-graph-algorithms#4]
Hey, I'm using your algorithms for a University project and when adding my own data set and running Dijkstra it froze and cant reach anywhere! I believe its an error when trying to find a path to an unreachable node. Do you have any knowledge about that? Or it is just something wrong with my code? Please help me ASAP. Thanks a lot!

**Comment by brianstorti** [comment]
Yeah, the current implementation doesn't handle unreachable paths. It depends on what you want to do in this case, if you just want to raise an exception when that happens, for example, you can change the code to something like this:

```diff
  def shortest_path_to(node)
    path = []
    while node != @source_node
      path.unshift(node)
      node = @path_to[node]
+     raise "No path found" if node.nil?
    end

    path.unshift(@source_node)
  end

```
